### ISSUE TITLE
Problem if using latest prism CI packages

### ISSUE THREAD

**Issue by dazinator** [dansiegel/Prism.Plugin.Popups#55]
I am using the CI feed and `7.0.0.423-ci` packages of `Prism` (Core and Forms), and `Prism.Plugin.Popups`

I am getting this exception:
> Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000015 (from typeref, class/assembly Prism.Navigation.INavigationService, Prism.Forms, Version=7.0.0.336, Culture=neutral, PublicKeyToken=null) occurred

Stack Trace:

>  at Prism.Plugin.Popups.PopupRegistrationExtensions.RegisterPopupNavigationService (Prism.Ioc.IContainerRegistry containerRegistry) [0x00000] in <c60d52f08263422c97812182b0c9c651>:0 
  at FlexForce3.Core.App.RegisterTypes (Prism.Ioc.IContainerRegistry Builder) [0x00001] in C:\Users\darrell.tunnell\Source\Repos\flexforce3\src\Shared\FlexForce3.Core\App.xaml.cs:119 
  at Prism.PrismApplicationBase.Initialize () [0x0002f] in <62e67d4e2a224ac39d77a6cc758b5406>:0 
  at Prism.PrismApplicationBase.InitializeInternal () [0x00006] in <62e67d4e2a224ac39d77a6cc758b5406>:0 
  at Prism.PrismApplicationBase..ctor (Prism.IPlatformInitializer initializer) [0x00031] in <62e67d4e2a224ac39d77a6cc758b5406>:0 
  at Prism.Autofac.PrismApplication.Initialize () [0x00000] in <6fb870dbdc264a6db6d781e8a4c6c3bb>:0 
  at FlexForce3.Core.App..ctor (Prism.IPlatformInitializer initializer, FlexForce3.Services.Contracts.ILoginService loginService) [0x00000] in C:\Users\darrell.tunnell\Source\Repos\flexforce3\src\Shared\FlexForce3.Core\App.xaml.cs:40 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in /Users/builder/jenkins/workspace/xamarin-android-d15-5/xamarin-android/external/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:661 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/jenkins/workspace/xamarin-android-d15-5/xamarin-android/external/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) [0x00065] in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00095] in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient (Microsoft.Extensions.DependencyInjection.ServiceLookup.TransientCallSite transientCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) [0x00008] in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x000a3] in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) [0x00000] in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider+<>c__DisplayClass22_0.<RealizeService>b__0 (Microsoft.Extensions.DependencyInjection.ServiceProvider provider) [0x00034] in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) [0x00025] in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService (System.IServiceProvider provider, System.Type serviceType) [0x00034] in <b382408329ee4512a838fca9f4a05f42>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T] (System.IServiceProvider provider) [0x0000e] in <b382408329ee4512a838fca9f4a05f42>:0 
  at FlexForce3.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x000a8] in C:\Users\darrell.tunnell\Source\Repos\flexforce3\src\Native\FlexForce3.Droid\MainActivity.cs:85 

I assume there has been some breaking change in the latest CI packages witn `INavigationService` since 7.0.0.336,

**Comment by dazinator** [comment]
And simple workaround was to just use this:

```
  Builder.RegisterInstance<IPopupNavigation>(PopupNavigation.Instance);
  Builder.Register<INavigationService, PopupPageNavigationService>(PrismApplicationBase.NavigationServiceName);

```

rather than this:

```
Builder.RegisterPopupNavigationService();
```

**Comment by dansiegel** [comment]
if you're using the latest from CI... you shouldn't be using the Builder at all... all container specific packages were deprecated use the Prism.Plugin.Popups nuget instead this should register what you need with the ContainerRegistry.

**Comment by dazinator** [comment]
@dansiegel 

I am using `Prism.Plugin.Popups` nuget package!
I believe you still have to use the extension method: `RegisterPopupNavigationService()` to add the services is that correct? or does simply referencing the nuget package now enough to atumagically register services?

Because the problem is the extension method - it is compiled against a type `INavigationService` in `7.0.0.336`. `INavigationService` type has changes shape in latest CI builds (method signatures changed) 
 and this is why if you are using `7.0.0.423-ci` and call `RegisterPopupNavigationService()` you get the exception I have logged above.

**Comment by dansiegel** [comment]
if you're targeting a Prism CI package currently INavigationService has moved from Prism.Forms to Prism.Core which will break the Popup Plugin. I will have a CI package out soon that will fix that but I need to release and updated preview package first.

**Comment by dazinator** [comment]
Ok cheers just wanted to raise awareness of this issue incase it wasnt already on the radar

**Comment by dansiegel** [comment]
@dazinator much appreciated... I certainly have a lot to do, and sometimes I forget to create issues, so it's good that you did, it gives us a place to track the issue :)

**Comment by dazinator** [comment]
This issue also appears to break the linker:

> Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Prism.Navigation.INavigationService' (defined in assembly 'Prism.Plugin.Popups, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Prism.Forms, Version=7.0.0.336, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Prism.Navigation.INavigationService
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkFields(TypeDefinition type, Boolean includeStatic, Boolean markBackingFieldsOnlyIfPropertyMarked)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	FlexForce3.Droid	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1696

**Comment by dazinator** [comment]
Are you open to a PR that bumps these dependencies?

**Comment by dazinator** [comment]
I'll submit a PR anyway. There were breaking changes in various interfaces around navigation that I'll address. For example the method signatures from `INavigationAware` were changed to accept `INavigationParameters` rather than `NavigationParameters` etc

**Comment by dazinator** [comment]
PR submitted

**Comment by dansiegel** [comment]
@dazinator I need to ship a new preview package first. I’m also trying to determine a timeframe for releasing the next service release for Prism which could alter releases here.

**Comment by dansiegel** [comment]
The latest CI package on [MyGet](https://myget.org/gallery/prism-plugins) now supports the Prism CI packages

**Comment by dansiegel** [comment]
This has now been updated to work with the Prism 7.1 preview on NuGet

**Comment by dazinator** [comment]
Great stuff thanks.
